# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"\x12\n\x10HeartbeatRequest\"\x15\n\x13HeartbeatOkResponse\"=\n\x16InstanceMetricsRequest\x12\x10\n\x08\x63pu_load\x18\x01 \x01(\x02\x12\x11\n\thttp_load\x18\x02 \x01(\x02\"\x1b\n\x19InstanceMetricsOkResponse2\x92\x01\n\x0eMonitorService\x12\x36\n\tHeartbeat\x12\x11.HeartbeatRequest\x1a\x14.HeartbeatOkResponse\"\x00\x12H\n\x0fInstanceMetrics\x12\x17.InstanceMetricsRequest\x1a\x1a.InstanceMetricsOkResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEARTBEATREQUEST._serialized_start=18
  _HEARTBEATREQUEST._serialized_end=36
  _HEARTBEATOKRESPONSE._serialized_start=38
  _HEARTBEATOKRESPONSE._serialized_end=59
  _INSTANCEMETRICSREQUEST._serialized_start=61
  _INSTANCEMETRICSREQUEST._serialized_end=122
  _INSTANCEMETRICSOKRESPONSE._serialized_start=124
  _INSTANCEMETRICSOKRESPONSE._serialized_end=151
  _MONITORSERVICE._serialized_start=154
  _MONITORSERVICE._serialized_end=300
# @@protoc_insertion_point(module_scope)
