# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import monitor_pb2 as monitor__pb2


class MonitorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/protos.MonitorService/Heartbeat',
                request_serializer=monitor__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=monitor__pb2.HeartbeatOkResponse.FromString,
                )
        self.InstanceMetrics = channel.unary_unary(
                '/protos.MonitorService/InstanceMetrics',
                request_serializer=monitor__pb2.InstanceMetricsRequest.SerializeToString,
                response_deserializer=monitor__pb2.InstanceMetricsOkResponse.FromString,
                )


class MonitorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InstanceMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonitorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=monitor__pb2.HeartbeatRequest.FromString,
                    response_serializer=monitor__pb2.HeartbeatOkResponse.SerializeToString,
            ),
            'InstanceMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.InstanceMetrics,
                    request_deserializer=monitor__pb2.InstanceMetricsRequest.FromString,
                    response_serializer=monitor__pb2.InstanceMetricsOkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.MonitorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MonitorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.MonitorService/Heartbeat',
            monitor__pb2.HeartbeatRequest.SerializeToString,
            monitor__pb2.HeartbeatOkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InstanceMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.MonitorService/InstanceMetrics',
            monitor__pb2.InstanceMetricsRequest.SerializeToString,
            monitor__pb2.InstanceMetricsOkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
