# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/monitor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/monitor.proto\x12\x06protos\"\x12\n\x10HeartbeatRequest\"%\n\x13HeartbeatOkResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\"\x18\n\x16InstanceMetricsRequest\"-\n\x19InstanceMetricsOkResponse\x12\x10\n\x08\x63pu_load\x18\x01 \x01(\x02\x32\xae\x01\n\x0eMonitorService\x12\x44\n\tHeartbeat\x12\x18.protos.HeartbeatRequest\x1a\x1b.protos.HeartbeatOkResponse\"\x00\x12V\n\x0fInstanceMetrics\x12\x1e.protos.InstanceMetricsRequest\x1a!.protos.InstanceMetricsOkResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.monitor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEARTBEATREQUEST._serialized_start=32
  _HEARTBEATREQUEST._serialized_end=50
  _HEARTBEATOKRESPONSE._serialized_start=52
  _HEARTBEATOKRESPONSE._serialized_end=89
  _INSTANCEMETRICSREQUEST._serialized_start=91
  _INSTANCEMETRICSREQUEST._serialized_end=115
  _INSTANCEMETRICSOKRESPONSE._serialized_start=117
  _INSTANCEMETRICSOKRESPONSE._serialized_end=162
  _MONITORSERVICE._serialized_start=165
  _MONITORSERVICE._serialized_end=339
# @@protoc_insertion_point(module_scope)
